import {
  useTrending,
  useTrendingMovies,
  useTrendingTV,
  usePopularMovies,
  useTopRatedMovies,
  useUpcomingMovies,
  useActionMovies,
  useComedyMovies,
  useHorrorMovies,
  useRomanceMovies,
  useThrillerMovies,
  usePopularTV,
  useTopRatedTV,
  useActionTV,
  useComedyTV,
  useDramaTV,
  useCrimeTV,
  useNetflixOriginals,
  useTrendingAnime,
  usePopularAnime,
  useTopRatedAnime,
  useActionAnime,
  useAnimeTV,
  useAnimeMovies,
} from "@/hooks/api/useMovies";

export const HOOK_MAP: Record<string, () => ReturnType<typeof useTrending>> = {
  trending: useTrending,
  trendingMovies: useTrendingMovies,
  trendingTV: useTrendingTV,
  popularMovies: usePopularMovies,
  topRatedMovies: useTopRatedMovies,
  upcomingMovies: useUpcomingMovies,
  actionMovies: useActionMovies,
  comedyMovies: useComedyMovies,
  horrorMovies: useHorrorMovies,
  romanceMovies: useRomanceMovies,
  thrillerMovies: useThrillerMovies,
  popularTV: usePopularTV,
  topRatedTV: useTopRatedTV,
  actionTV: useActionTV,
  comedyTV: useComedyTV,
  dramaTV: useDramaTV,
  crimeTV: useCrimeTV,
  netflixOriginals: useNetflixOriginals,
  trendingAnime: useTrendingAnime,
  popularAnime: usePopularAnime,
  topRatedAnime: useTopRatedAnime,
  actionAnime: useActionAnime,
  animeTV: useAnimeTV,
  animeMovies: useAnimeMovies,
};
